- node/cli/src/cli.rs
- node/cli/src/command.rs
Use env variable `UNIQUE_NODE_NAME` value as node name
> Use env var as node name

- node/cli/src/chain_spec.rs
- node/cli/src/service.rs
Fixed the node: now it is able to compile at work without the default features
> Fix node to work without default features

- pallets/unique/src/eth/sponsoring.rs
- pallets/unique/src/sponsorship.rs
> Handle sponsoring for ERC721Mintable

- pallets/common/src/benchmarking.rs
- pallets/nonfungible/src/lib.rs
- pallets/proxy-rmrk-core/src/lib.rs
- primitives/data-structs/src/lib.rs
- tests/src/eth/util/helpers.ts
- tests/src/interfaces/augment-api-errors.ts
- tests/src/interfaces/augment-api-query.ts
- tests/src/interfaces/augment-api-tx.ts
- tests/src/interfaces/default/types.ts
- tests/src/interfaces/lookup.ts
- tests/src/interfaces/types-lookup.ts
- tests/src/nesting/nest.test.ts
[CORE-413](https://cryptousetech.atlassian.net/browse/CORE-413)
> CORE-413: Nesting: Collection Admin test suite

- pallets/common/src/lib.rs
- primitives/data-structs/src/lib.rs
- tests/src/approve.test.ts
- tests/src/burnItem.test.ts
- tests/src/eth/crossTransfer.test.ts
- tests/src/limits.test.ts
- tests/src/nesting/graphs.test.ts
- tests/src/nesting/nest.test.ts
- tests/src/transferFrom.test.ts
- tests/src/util/helpers.ts
> OwnerCanTransfer flag

- Cargo.lock
- client/rpc/Cargo.toml
- crates/evm-coder/Cargo.toml
- node/cli/Cargo.toml
- node/rpc/Cargo.toml
- pallets/common/Cargo.toml
- pallets/evm-coder-substrate/Cargo.toml
- pallets/evm-contract-helpers/Cargo.toml
- pallets/evm-migration/Cargo.toml
- pallets/evm-transaction-payment/Cargo.toml
- pallets/fungible/Cargo.toml
- pallets/inflation/Cargo.toml
- pallets/nonfungible/Cargo.toml
- pallets/proxy-rmrk-core/Cargo.toml
- pallets/proxy-rmrk-equip/Cargo.toml
- pallets/refungible/Cargo.toml
- pallets/scheduler/Cargo.toml
- pallets/structure/Cargo.toml
- pallets/unique/Cargo.toml
- primitives/data-structs/Cargo.toml
- primitives/rmrk-rpc/Cargo.toml
- primitives/rpc/Cargo.toml
- runtime/common/Cargo.toml
- runtime/opal/Cargo.toml
- runtime/quartz/Cargo.toml
- runtime/tests/Cargo.toml
- runtime/unique/Cargo.toml
> feat: upgrade to polkadot-v0.9.24

- chain-specs/quartz.json
- chain-specs/unique.json
> change chain-specs

- launch-config-full-moonriver.json
- launch-testnet-full-moonriver.sh
- tests/package.json
- tests/src/xcmTransferMoonriver.test.ts
xTokens pallet support needed (branch `feature/multi-assets-statemine-demo` would work).
> [CORE-496] Moonriver/QTZ Transfer

- Cargo.lock
- pallets/evm-coder-substrate/CHANGELOG.md
- pallets/evm-coder-substrate/Cargo.toml
- pallets/evm-coder-substrate/src/lib.rs
- tests/src/evmCoder.test.ts
… is called on collection contract
> Fix: add error when non existing function is called

- tests/src/util/playgrounds/unique.ts
In addition, shift default amounts of tokens in functions down to 1 (minimum/guaranteed to always be the case); introduce functions to remove admins and enable allow-list; and add more documentation.
> Tests (util): Replace label with native error message + more functions + more docs

- tests/src/addToContractAllowList.test.ts
- tests/src/block-production.test.ts
- tests/src/connection.test.ts
- tests/src/contracts.test.ts
- tests/src/enableContractSponsoring.test.ts
- tests/src/evmCoder.test.ts
- tests/src/setContractSponsoringRateLimit.test.ts
- tests/src/util/playgrounds/index.ts
To merge after Logging (https://github.com/UniqueNetwork/unique-chain/pull/601)
> Tests: Finish refactoring base folder (hopefully)

- tests/src/app-promotion.test.ts
- tests/src/burnItem.test.ts
- tests/src/fungible.test.ts
- tests/src/refungible.test.ts
- tests/src/util/playgrounds/unique.ts
Move burnItemTests to playgrounds
+ fix appPromotion flaky test
> Move burnItemTests to playgrounds

- .github/workflows/ci-develop.yml
- .github/workflows/ci-master.yml
- .github/workflows/codestyle_v2.yml
- .github/workflows/dev-build-tests_v2.yml
- .github/workflows/forkless-update-data_v2.yml
- .github/workflows/forkless-update-nodata_v2.yml
- .github/workflows/market-test_v2.yml
- .github/workflows/node-only-update_v2.yml
- .github/workflows/test_codestyle_v2.yml
- .github/workflows/try-runtime_v2.yml
- .github/workflows/unit-test_v2.yml
Документирование + очистка от неиспользуемых workflow файлов.
> Rapid parallel start v2 docs

- runtime/common/config/pallets/app_promotion.rs
`PendingInterval` is set in parachain blocks.
> fix timing for pending interval `appPromotion` pallet

- tests/src/app-promotion.test.ts
- tests/src/util/globalSetup.ts
- tests/src/util/index.ts
It works fine on dev node but fails on regular
> Increase app-promotion periods for full node

- tests/src/benchmarks/mintFee/benchmark.ts
- tests/src/benchmarks/mintFee/proxyContract.sol
Fixed bugs caused by changes in the signatures of interface functions and data structures
> fix: bencmark for fee calculation

- Cargo.lock
- pallets/common/CHANGELOG.md
- pallets/common/Cargo.toml
- pallets/common/src/lib.rs
- pallets/fungible/src/common.rs
- pallets/nonfungible/CHANGELOG.md
- pallets/nonfungible/Cargo.toml
- pallets/nonfungible/src/common.rs
- pallets/nonfungible/src/erc.rs
- pallets/refungible/CHANGELOG.md
- pallets/refungible/Cargo.toml
- pallets/refungible/src/common.rs
- pallets/refungible/src/erc.rs
- pallets/unique/src/lib.rs
- runtime/common/weights.rs
Chnaged behaviour for `CommonWeightInfo` trait.
> fix: weight for `createItem`

- Cargo.lock
- node/cli/src/chain_spec.rs
- pallets/app-promotion/CHANGELOG.md
- pallets/app-promotion/Cargo.toml
- pallets/app-promotion/src/lib.rs
- pallets/common/CHANGELOG.md
- pallets/common/Cargo.toml
- pallets/common/src/lib.rs
- pallets/nonfungible/CHANGELOG.md
- pallets/nonfungible/Cargo.toml
- pallets/nonfungible/src/lib.rs
- AppPromo
- Common
- NonFungible
> fix: unused `on_runtime_upgrade()` was removed

- Cargo.lock
- pallets/app-promotion/CHANGELOG.md
- pallets/app-promotion/Cargo.toml
- pallets/app-promotion/src/benchmarking.rs
- pallets/app-promotion/src/lib.rs
- pallets/app-promotion/src/types.rs
- pallets/nonfungible/src/benchmarking.rs
- pallets/refungible/src/benchmarking.rs
> feat(app-promo): types for `Currency` trait support has been removed

- js-packages/scripts/councilproposal.ts
- js-packages/scripts/hrmpchannel.ts
- js-packages/scripts/package.json
- js-packages/scripts/proposeupgrade.ts
HrmpChannel script Usage:
```
yarn hrmpChannel <RELAY_URL> <OUR_CHAIN_URL> <OTHER_CHAIN_URL> <open | accept>
```
> scripts: hrmp channels proposal + fixes

- Cargo.lock
- pallets/foreign-assets/Cargo.toml
- pallets/foreign-assets/src/lib.rs
> migrate foreign asset to v4 + fix foreign flags
